### ISSUE TITLE
Error loading emulator from hdf5 file

### ISSUE THREAD

**Issue by malapradej** [jgomezdans/gp_emulator#5]
Can't load an emulator from an hdf5 emulator file. Emulators are in file libradtran_emulators.h5 with typical group name eg. 'toa_refl_020_030_135' and datasets and names exactly as found in original npz files. A typical h5dump of the above group:

    $ h5dump -H -g toa_refl_020_030_135 libradtran_emulators.h5
    HDF5 "libradtran_emulators.h5" {
    GROUP "toa_refl_020_030_135" {
       DATASET "X_train" {
          DATATYPE  H5T_IEEE_F64LE
          DATASPACE  SIMPLE { ( 250, 5201 ) / ( 250, 5201 ) }
       }
       DATASET "basis_functions" {
          DATATYPE  H5T_IEEE_F64LE
          DATASPACE  SIMPLE { ( 10, 5201 ) / ( 10, 5201 ) }
       }
       DATASET "hyperparams" {
          DATATYPE  H5T_IEEE_F64LE
          DATASPACE  SIMPLE { ( 8, 10 ) / ( 8, 10 ) }
       }
       DATASET "n_pcs" {
          DATATYPE  H5T_STD_I64LE
          DATASPACE  SCALAR
       }
       DATASET "thresh" {
          DATATYPE  H5T_IEEE_F64LE
          DATASPACE  SCALAR
       }
       DATASET "y_train" {
          DATATYPE  H5T_IEEE_F64LE
          DATASPACE  SIMPLE { ( 250, 6 ) / ( 250, 6 ) }
       }
    }
    }

When reading the emulator using the code:

    sza = 20
    vza = 30
    raa = 135
    #load emulator and emulate based on above parameters
    import gp_emulator
    emu = gp_emulator.MultivariateEmulator(dump='../../Data/LUT/libradtran_emulators.h5', model='toa_refl', sza=sza, vza=vza, raa=raa)

The following error occurs:

    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-104-1c7f6944112e> in <module>()
          1 #load emulator and emulate based on above parameters
          2 import gp_emulator
    ----> 3 emu = gp_emulator.MultivariateEmulator(dump='../../Data/LUT/libradtran_emulators.h5', model='toa_refl', sza=sza, vza=vza, raa=raa)

    /usr/local/lib/python2.7/dist-packages/gp_emulator/multivariate_gp.pyc in __init__(self, dump, X, y, hyperparams, model, sza, vza, raa, thresh, n_tries)
         74                 f = h5py.File ( dump, 'r+')
         75                 group = "/%s_%03d_%03d_%03d" % ( model, sza, vza, raa )
    ---> 76                 X = f[group + '/X_train'][:,:]
         77                 y = f[group + '/y_train'][:,:]
         78                 hyperparams = f[group+'/hyperparams'][:,:]

    /usr/lib/python2.7/dist-packages/h5py/_hl/group.pyc in __getitem__(self, name)
        151                 raise ValueError("Invalid HDF5 object reference")
        152         else:
    --> 153             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
        154 
        155         otype = h5i.get_type(oid)

    h5o.pyx in h5py.h5o.open (h5py/h5o.c:3403)()

    KeyError: "unable to open object (Symbol table: Can't open object)"

It is possible to open the file using h5py module and query the dataset using:

    import h5py
    h5 = h5py.File('../../Data/LUT/libradtran_emulators.h5', 'r')
    grp = h5['toa_refl_20_30_135']
    grp['X_train']
    
    <HDF5 dataset "X_train": shape (250, 5201), type "<f8">

**Comment by jgomezdans** [comment]
Is the file available in the UCL system so I can poke a bit at it?

**Comment by malapradej** [comment]
I think I found the problem. If we remove the redundant forward slash on line 75 of multivariate_gp.py file it works. Should be:

    75                 group = "%s_%03d_%03d_%03d" % ( model, sza, vza, raa )

**Comment by jgomezdans** [comment]
Probably nailed it there, can you make a PR please?

**Comment by malapradej** [comment]
I think I made a copy in the /storage/.../libradtran_emu folder. Although this copy still has the 'toa_refl_00_00_000' format for groups. 
No probs I'll send a pull request :)
